#!/bin/sh

#############################################################################
#
#  $Id: gp-log-offs-3 1.2 2013/11/14 16:12:27 martin TRASH $
#
#  Description:
#    Plot logfiles created by the Meinberg Time Adjustment Service
#    using gnuplot.
#
#    (c) Martin Burnicki <martin.burnicki@meinberg.de>
#
# ---------------------------------------------------------------------------
#  $Log: gp-log-offs-3 $
#  Revision 1.2  2013/11/14 16:12:27  martin
#  Use common include file gp_common.
#  Revision 1.1  2013/11/14 11:40:35  martin
#
#############################################################################

. gp-common

while [ $# -gt 0 ]; do

  init_mbgadjtm_graph $1

  cd $basedir && echo "\
    $term_opts \
    $frame_opts \
    set multiplot; \
    set size 1.0, 0.33333; \
    set xrange $x; \
    \
    set notitle; \
    set xlabel \"$this_xlabel\"; \
    set format x \"$this_format_x\"; \
    \
    set origin 0.0, 0.0; \
    set ylabel \"$tick_label\"; \
    set format y \"$tick_format\"; \
    set yrange $tick; \
    plot \"$1\" using $tick_vals with lines; \
    \
    set noxlabel; \
    set format x \"\"; \
    \
    set origin 0.0, 0.33333; \
    set xzeroaxis linetype -1; \
    set ylabel \"$delta_t_label\"; \
    set format y \"$delta_t_format\"; \
    set yrange $delta_t; \
    plot \"$1\" using $delta_t_vals with lines; \
    \
    set title \"$this_title\"; \
    \
    set origin 0.0, 0.66666; \
    set ylabel \"$acc_time_label\"; \
    set format y \"$acc_time_format\"; \
    set yrange $acc_time; \
    plot \"$1\" using $acc_time_vals with lines; \
    \
    "|gnuplot -persist

    shift;
done

