#!/bin/sh

#############################################################################
#
#  $Id: gp-mbgcmptime 1.1 2013/11/14 11:40:36 martin TRASH $
#
#  Description:
#    Plot time offsets reported by  mbgsvcd.
#
#    (c) Martin Burnicki <martin.burnicki@meinberg.de>
#
#  Some parameters can be overridden on the command line, e.g.:
#
#    x=[0:100]                  limit x range (time) from 0 to 100
#    time_offs=[-0.003:0.003]   limit time offset range from -3 to 3
#    freq_offs=[*:*]            auto scale frequency offset (the default)
#    roundtrip=[0:*]            limit roundtrip range from 0 to auto
#
# ---------------------------------------------------------------------------
#  $Log: gp-mbgcmptime $
#  Revision 1.1  2013/11/14 11:40:36  martin
#  Revision 1.1.1.1  2011/03/16 16:14:37  martin
#  Read date/time from file for x-axis.
#  Revision 1.1  2011/03/16 16:07:24  martin
#
#############################################################################

. gp-common $@

init_graph()
{
#  set_mjd_tod $1;
  set_term_opts $1;

  mjd_col='1';
  tod_col='2';
  x_vals="((\$$tod_col-$this_tod)+(\$$mjd_col-$this_mjd)*86400)";

  if test -z "$x"; then
    x=$auto_range;
  fi;


  time_offs_col='6'
#  time_offs_vals="(\$$time_offs_col*1000)"
  time_offs_vals="(\$$time_offs_col/1000)"

  if test -z "$time_offs"; then
    time_offs=$auto_range;
  fi;
}


while [ $# -gt 0 ]; do

  init_graph $1

  cd $basedir && echo "\
    $term_opts \
    $frame_opts \
    set multiplot; \
    set size 1.0, 1.0; \
    \
    set origin 0.0, 0.0; \
    \
    set title \"File: $1\"; \
    \
    set ylabel 'time offs [ms]'; \
    set yrange $time_offs; \
    set format y \"%.3f\"; \
    set xrange $x; \
    set xzeroaxis lt -1; \
    plot \"$1\" using $time_offs_vals with lines; \
    " |gnuplot -persist

    shift;
done
