#!/bin/sh

#############################################################################
#
#  $Id: gp-mrs-stats 1.2.1.1 2014/02/06 16:38:28 martin TRASH $
#
#  Description:
#    Plot MRS statistic files using gnuplot.
#
#    (c) Martin Burnicki <martin.burnicki@meinberg.de>
#
#    Two graphs are plotted above each other, using the same time range x,
#    and selected MRS sources t1 and t2, which can be selected from:
#    gps, pps, irig, ntp, ptp, and frq
#
#    Some parameters can be overridden on the command line, e.g.:
#
#    x=[0:100]                  limit x range (time) from 0 to 100
#    x=[100:*]                  start x min at 100, auto scale x max
#    t1=ptp                     select PTP offsets for t1, default: gps
#    t2=pps                     select PPS offsets for t1, default: ntp
#    time_offs=[-0.003:0.003]   limit common time offset range from -3 to 3
#    t1_offs=[-0.001:0.001]     limit t1 only time offset range from -3 to 3
#    t2_bias=2.5                add bias 2.5 to t2 osffset range
#
# ---------------------------------------------------------------------------
#  $Log: gp-mrs-stats $
#  Revision 1.2.1.1  2014/02/06 16:38:28  martin
#  Started to use new syntax.
#  Revision 1.2  2014/02/06 14:41:01  martin
#  Moved some stuff to gp-common.
#  Use common syntax.
#  Revision 1.1  2010/03/24 14:21:39  martin
#  Initial revision.
#
#############################################################################

# uncomment to override defaults
#if test -z "$lmargin"; then
#  lmargin=17;
#fi;

. gp-common $@

while [ $# -gt 0 ]; do

  init_graph_mrs $1

  cd $basedir && gnuplot -persist << EOF
    $term_opts
    $frame_opts
    set multiplot
    set size 1.0, 0.5
    set xrange $x

    unset title
    set xlabel "$this_xlabel"
    set format x "$this_format_x"

    set origin 0.0, 0.0
    set xzeroaxis linetype -1
    set ylabel "$t2_label"
    set format y "$t2_format_y"
    set yrange $t2_offs
    plot "$1" using $x_vals:$t2_vals with lines linestyle 1
    $hor_line_t2

    unset xlabel
    set format x ""

    set title "$this_title"

    set origin 0.0, 0.5
    set xzeroaxis linetype -1
    set ylabel "$t1_label"
    set format y "$t1_format_y"
    set yrange $t1_offs
    plot "$1" using $x_vals:$t1_vals with lines linestyle 1
    $hor_line_t1
EOF
# EOF above needs to be at the *beginning* of the line.

  shift
done
