#!/bin/sh

#############################################################################
#
# Plot time offsets reported by mbgsvcd.
#
# (c) Martin Burnicki <martin.burnicki@meinberg.de>
#
# Some parameters can be overridden on the command line, e.g.:
#
#   x=[0:100]                  limit x range (time) from 0 to 100
#   time_offs=[-0.003:0.003]   limit time offset range from -3 to 3
#   freq_offs=[*:*]            auto scale frequency offset (the default)
#
#############################################################################

. gp-common $@

init_graph()
{
#  set_mjd_tod $1;
  set_term_opts $1;

  mjd_col='1';
  tod_col='2';
#  x_vals="((\$$tod_col-$this_tod)+(\$$mjd_col-$this_mjd)*86400)";

  if test -z "$x"; then
    x=$auto_range;
  fi;

#  set xdata time
#  set timefmt "%Y-%m-%d %H:%M:%S"

  time_offs_col='5'
  time_offs_vals="(\$$time_offs_col*1000)"
#  time_offs_vals="(\$$time_offs_col)"

  if test -z "$time_offs"; then
    time_offs=$auto_range;
  fi;
}



while [ $# -gt 0 ]; do

  init_graph $1

  cd $basedir && gnuplot -persist << EOF
    $term_opts
    $frame_opts
    set multiplot
    set size 1.0, 1.0

    set origin 0.0, 0.0

    set title "File: $1"

    set ylabel 'time offs [ms]'
    set yrange $time_offs
    set format y "%.3f"
    plot "$1" using $time_offs_vals with lines
EOF
# EOF above needs to be at the *beginning* of the line.

  shift
done
