#!/bin/sh

#############################################################################
#
#  $Id: gp-ntp-peerstats 1.3 2013/11/14 17:01:02 martin TRASH $
#
#  Description:
#    Plot NTP peerstats files using gnuplot.
#
#    (c) Martin Burnicki <martin.burnicki@meinberg.de>
#
#  ATTENTION:
#    By default NTP peerstats files contain statistic info for all
#    configured peers. However, it makes more sense to visualize only the
#    statistics for a single peer, so the relevant information should
#    be sorted out into a temporary file, e.g.:
#
#      cat peerstats | grep 172.16.3.1 > peeerstats.tmp
#
#    The temporary file should then be displayed.
#
#  Some parameters can be overridden on the command line, e.g.:
#
#    x=[0:100]                  limit x range (time) from 0 to 100
#    time_offs=[-0.003:0.003]   limit time offset range from -3 to 3
#    round_trip=[*:*]           auto scale frequency offset (the default)
#    round_trip=[0:*]           limit roundtrip range from 0 to auto
#
# ---------------------------------------------------------------------------
#  $Log: gp-ntp-peerstats $
#  Revision 1.3  2013/11/14 17:01:02  martin
#  Use common init function.
#  Unified syntax and usage of variables.
#  Revision 1.2  2010/03/24 12:07:49  martin
#  Moved set_mjd_tod() to gp-common.
#  Revision 1.1  2010/02/04 10:17:23  martin
#
#############################################################################

. gp-common $@

while [ $# -gt 0 ]; do

  init_ntp_graph $1

  cd $basedir && echo "\
    $term_opts \
    $frame_opts \
    set multiplot; \
    set size 1.0, 0.5; \
    set xrange $x; \
    \
    set notitle; \
    set xlabel \"$this_xlabel\"; \
    set format x \"$this_format_x\"; \
    \
    set origin 0.0, 0.0; \
    set ylabel \"$round_trip_label\"; \
    set format y \"$round_trip_format\"; \
    set yrange $round_trip; \
    plot \"$1\" using $x_vals:$round_trip_vals with lines; \
    \
    set noxlabel; \
    set format x \"\"; \
    \
    set title \"$this_title\"; \
    \
    set origin 0.0, 0.5; \
    set xzeroaxis linetype -1; \
    set ylabel \"$time_offs_label\"; \
    set format y \"$time_offs_format\"; \
    set yrange $time_offs; \
    plot \"$1\" using $x_vals:$peer_time_offs_vals with lines; \
    \
    " |gnuplot -persist

    shift;
done
