#!/bin/sh

#############################################################################
#
#  $Id: gp-ntp-loopstats 1.6 2014/02/06 14:09:49 martin TRASH $
#
#  Description:
#    Plot NTP loopstats files using gnuplot.
#
#    (c) Martin Burnicki <martin.burnicki@meinberg.de>
#
#  Some parameters can be overridden on the command line, e.g.:
#
#    x=[0:100]                  limit x range (time) from 0 to 100
#    time_offs=[-0.003:0.003]   limit time offset range from -3 to 3
#    freq_offs=[*:*]            auto scale frequency offset (the default)
#    roundtrip=[0:*]            limit roundtrip range from 0 to auto
#
# ---------------------------------------------------------------------------
#  $Log: gp-ntp-loopstats $
#  Revision 1.6  2014/02/06 14:09:49  martin
#  Account for renamed function.
#  Revision 1.5  2013/11/14 17:01:37  martin
#  Moved init function to common include file.
#  Revision 1.4  2013/11/14 16:39:10  martin
#  Unified syntax and usage of variables.
#  Revision 1.3  2010/03/24 12:07:49  martin
#  Moved set_mjd_tod() to gp-common.
#  Revision 1.2  2010/03/11 14:46:17  martin
#  Modified time offset label.
#  Revision 1.1  2010/02/03 16:01:51  martin
#  Initial revision.
#
#############################################################################

. gp-common $@

while [ $# -gt 0 ]; do

  init_graph_ntp $1

  cd $basedir && echo "\
    $term_opts \
    $frame_opts \
    set multiplot; \
    set size 1.0, 0.5; \
    set xrange $x; \
    \
    set notitle; \
    set xlabel \"$this_xlabel\"; \
    set format x \"$this_format_x\"; \
    \
    set origin 0.0, 0.0; \
    set ylabel \"$freq_offs_label\"; \
    set format y \"$freq_offs_format\"; \
    set yrange $freq_offs; \
    plot \"$1\" using $x_vals:$freq_offs_vals with lines; \
    \
    set noxlabel; \
    set format x \"\"; \
    \
    set title \"$this_title\"; \
    \
    set origin 0.0, 0.5; \
    set xzeroaxis linetype -1; \
    set ylabel \"$time_offs_label\"; \
    set format y \"$time_offs_format\"; \
    set yrange $time_offs; \
    plot \"$1\" using $x_vals:$loop_time_offs_vals with lines; \
    \
    " |gnuplot -persist

    shift;
done
