#!/bin/bash

#############################################################################
#
# Plot NTP loopstats files using gnuplot.
#
# (c) Martin Burnicki <martin.burnicki@meinberg.de>
#
# Some parameters can be overridden on the command line, e.g.:
#
#   x=[0:100]                  limit x range (time) from 0 to 100
#   time_offs=[-0.003:0.003]   limit time offset range from -3 to 3
#   freq_offs=[*:*]            auto scale frequency offset (the default)
#   roundtrip=[0:*]            limit roundtrip range from 0 to auto
#
#############################################################################

. gp-common $@

while [ $# -gt 0 ]; do

  init_graph_ntp $1

  cd $basedir && gnuplot -persist << EOF
    $term_opts
    $frame_opts
    set multiplot
    set size 1.0, 0.5
    set xrange $x

    set notitle
    set xlabel "$this_xlabel"
    set format x "$this_format_x"

    set origin 0.0, 0.0
    set ylabel "$freq_offs_label"
    set format y "$freq_offs_format"
    set yrange $freq_offs
    plot "$1" using $x_vals:$freq_offs_vals with lines

    set noxlabel
    set format x ""

    set title "$this_title"

    set origin 0.0, 0.5
    set xzeroaxis linetype -1
    set ylabel "$time_offs_label"
    set format y "$time_offs_format"
    set yrange $time_offs
    plot "$1" using $x_vals:$loop_time_offs_vals with lines
EOF
# EOF above needs to be at the *beginning* of the line.

  shift
done
