#!/bin/bash

tgt_dir="/usr/local/bin"

# Determine the full path to our repo.
long_repo_base_dir=$(git rev-parse --show-toplevel)

# If the repo is below the target path, we just use
# a short path for the links, otherwise the full path.

if [[ ${long_repo_base_dir} == *"${tgt_dir}/"* ]]; then
  # Use a short path.
  repo_base_dir=${long_repo_base_dir#"${tgt_dir}/"}
else
  # Use the full path
  repo_base_dir=${long_repo_base_dir}
fi

# echo "long_repo_base_dir: ${long_repo_base_dir}"
# echo "repo_base_dir: ${repo_base_dir}"
# echo ""


# For all files except this install script
# we create symbolic links in the target directory.

files=$(git ls-files)

for f in ${files}; do
  if [ "${f}" != "install" ]; then
    cmd="sudo ln -sf ${repo_base_dir}/${f} ${tgt_dir}/${f}"
    echo "${cmd}"
    eval "${cmd}"
  fi
done
